spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos-food
spring.datasource.username=postgres
spring.datasource.password=32213115
spring.datasource.driver-class-name=org.postgresql.Driver

spring.application.name=pedidos-ms
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
spring.flyway.validate-on-migrate=false