spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/alurafood_pagamento
spring.datasource.username=postgres
spring.datasource.password=32213115

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=pagamentos-ms
server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8085/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=false
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:0