server.port=8082
spring.application.name=gateway

eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
eureka.instance.prefer-ip-address=true

# Configuração de Rotas com Balanceamento e Remoção de Prefixo
spring.cloud.gateway.routes[0].id=pedidos-ms
spring.cloud.gateway.routes[0].uri=lb://pedidos-ms
spring.cloud.gateway.routes[0].predicates[0]=Path=/pedidos-ms/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=pagamentos-ms
spring.cloud.gateway.routes[1].uri=lb://pagamentos-ms
spring.cloud.gateway.routes[1].predicates[0]=Path=/pagamentos-ms/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/alurafood_gateway
spring.datasource.username=postgres
spring.datasource.password=32213115
spring.datasource.driver-class-name=org.postgresql.Driver